### ISSUE TITLE
Script does not exit

### ISSUE THREAD

**Issue by simonwinkler** [boutell/nj#1]
Hi. 

The script properly compiles the html files, but does not exit. I have to exit the process manually with the keyboard. 

Appending `process.exit();` to app.js has solved the problem for me. 

Kind regards, Simon

**Comment by boutell** [comment]
Weird. There's no async in this code anywhere (:

You might want to check out:

http://github.com/punkave/habit

**Comment by simonwinkler** [comment]
Thanks you for your reply

http://github.com/punkave/habit

I just had a look on habit and the following entry in the changelog came to my attention:

> Changelog
> 
> 0.3.4: added a process.exit(0) call to address a situation where habit does not otherwise terminate in node 0.12.7 on a Mac when installed globally. Despite chasing this with process._getActiveHandles and process._getActiveRequests I still don't know why.

I'm on node 0.12.7 so that may be related

**Comment by boutell** [comment]
Makes sense. A pull request would be great if you have a moment.

On Thu, Jan 28, 2016 at 10:47 AM, simonwinkler notifications@github.com
wrote:

> Thanks you for your reply
> 
> http://github.com/punkave/habit https://github.com/punkave/habit
> 
> I just had a look on habit and the following entry in the changelog came
> to my attention:
> 
> Changelog
> 
> 0.3.4: added a process.exit(0) call to address a situation where habit
> does not otherwise terminate in node 0.12.7 on a Mac when installed
> globally. Despite chasing this with process._getActiveHandles and
> process._getActiveRequests I still don't know why.
> 
> I'm on node 0.12.7 so that may be related
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/boutell/nj/issues/1#issuecomment-176243102.

## 

*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment]
Actually I'll just knock this out.

On Thu, Jan 28, 2016 at 10:48 AM, Tom Boutell tom@punkave.com wrote:

> Makes sense. A pull request would be great if you have a moment.
> 
> On Thu, Jan 28, 2016 at 10:47 AM, simonwinkler notifications@github.com
> wrote:
> 
> > Thanks you for your reply
> > 
> > http://github.com/punkave/habit https://github.com/punkave/habit
> > 
> > I just had a look on habit and the following entry in the changelog came
> > to my attention:
> > 
> > Changelog
> > 
> > 0.3.4: added a process.exit(0) call to address a situation where habit
> > does not otherwise terminate in node 0.12.7 on a Mac when installed
> > globally. Despite chasing this with process._getActiveHandles and
> > process._getActiveRequests I still don't know why.
> > 
> > I'm on node 0.12.7 so that may be related
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/boutell/nj/issues/1#issuecomment-176243102.
> 
> ## 
> 
> *THOMAS BOUTELL, *DEV & OPS
> P'UNK AVENUE | (215) 755-1330  |  punkave.com

## 

*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by simonwinkler** [comment]
Ok I'll make a pull request in the evening

**Comment by boutell** [comment]
Published a fix.

**Comment by simonwinkler** [comment]
Thanks!
